In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
cd ../analysis/

/srv/data/home/jlee782/segmentation/analysis


In [3]:
import pickle as pkl

In [4]:
from PixelEM import *

/home/jlee782/.local/lib/python2.7/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


In [7]:
sample_name = "5workers_rand0"
objid = 1

# Redundancy: verify that p in mask and p not in mask is the same accross all thresholds 

In [6]:
pinmask0 = pkl.load(open("pixel_em/5workers_rand0/obj1/isoGT_p_in_mask_2_thresh0.pkl"))
pinmaskn4 = pkl.load(open("pixel_em/5workers_rand0/obj1/isoGT_p_in_mask_2_thresh-4.pkl"))

In [11]:
pninmask0 = pkl.load(open("pixel_em/5workers_rand0/obj1/isoGT_p_not_in_mask_2_thresh0.pkl"))
pninmaskn4 = pkl.load(open("pixel_em/5workers_rand0/obj1/isoGT_p_not_in_mask_2_thresh-4.pkl"))

In [12]:
pninmask0

array([[-3.54043708, -3.54043708, -3.54043708, ..., -3.54043708,
        -3.54043708, -3.54043708],
       [-3.54043708, -3.54043708, -3.54043708, ..., -3.54043708,
        -3.54043708, -3.54043708],
       [-3.54043708, -3.54043708, -3.54043708, ..., -3.54043708,
        -3.54043708, -3.54043708],
       ..., 
       [-3.54043708, -3.54043708, -3.54043708, ..., -3.54043708,
        -3.54043708, -3.54043708],
       [-3.54043708, -3.54043708, -3.54043708, ..., -3.54043708,
        -3.54043708, -3.54043708],
       [-3.54043708, -3.54043708, -3.54043708, ..., -3.54043708,
        -3.54043708, -3.54043708]])

In [13]:
pninmaskn4

array([[-2.55412812, -2.55412812, -2.55412812, ..., -2.55412812,
        -2.55412812, -2.55412812],
       [-2.55412812, -2.55412812, -2.55412812, ..., -2.55412812,
        -2.55412812, -2.55412812],
       [-2.55412812, -2.55412812, -2.55412812, ..., -2.55412812,
        -2.55412812, -2.55412812],
       ..., 
       [-2.55412812, -2.55412812, -2.55412812, ..., -2.55412812,
        -2.55412812, -2.55412812],
       [-2.55412812, -2.55412812, -2.55412812, ..., -2.55412812,
        -2.55412812, -2.55412812],
       [-2.55412812, -2.55412812, -2.55412812, ..., -2.55412812,
        -2.55412812, -2.55412812]])

In [8]:
pinmask0

array([[-6.22143422, -6.22143422, -6.22143422, ..., -6.22143422,
        -6.22143422, -6.22143422],
       [-6.22143422, -6.22143422, -6.22143422, ..., -6.22143422,
        -6.22143422, -6.22143422],
       [-6.22143422, -6.22143422, -6.22143422, ..., -6.22143422,
        -6.22143422, -6.22143422],
       ..., 
       [-6.22143422, -6.22143422, -6.22143422, ..., -6.22143422,
        -6.22143422, -6.22143422],
       [-6.22143422, -6.22143422, -6.22143422, ..., -6.22143422,
        -6.22143422, -6.22143422],
       [-6.22143422, -6.22143422, -6.22143422, ..., -6.22143422,
        -6.22143422, -6.22143422]])

In [10]:
pinmaskn4

array([[-4.36077916, -4.36077916, -4.36077916, ..., -4.36077916,
        -4.36077916, -4.36077916],
       [-4.36077916, -4.36077916, -4.36077916, ..., -4.36077916,
        -4.36077916, -4.36077916],
       [-4.36077916, -4.36077916, -4.36077916, ..., -4.36077916,
        -4.36077916, -4.36077916],
       ..., 
       [-4.36077916, -4.36077916, -4.36077916, ..., -4.36077916,
        -4.36077916, -4.36077916],
       [-4.36077916, -4.36077916, -4.36077916, ..., -4.36077916,
        -4.36077916, -4.36077916],
       [-4.36077916, -4.36077916, -4.36077916, ..., -4.36077916,
        -4.36077916, -4.36077916]])

In [7]:
pinmask0 == pinmaskn4

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ..., 
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], dtype=bool)